from . import weighbridge_scale
from . import weighbridge_quality_type
from . import weighbridge_weighbridge
from . import weighbridge_quality_control
from . import weighbridge_scale_dashboard
from . import weighbridge_partner
from . import weighbridge_product
from . import weighbridge_load
from . import res_config_settings
