{
    "name": "Farm",
    "summary": """
        Farm Management System
    """,
    "author": "Witech Inovasi Indonesia.PT (Witech Enterprise)",
    "maintainers": ["BebyNLahagu199"],
    "website": "https://github.com/witech-io/base_addons",
    "category": "Manufacturing/Manufacturing",
    "version": "18.0.1.1.0",
    "depends": [
        "stock",
        "wi_base_qr_code",
        "hr",
        "mail",
        "account",
        "hr_contract",
        "uom",
        "wi_base_web_maps",
    ],
    "data": [
        "data/farm_base_data.xml",
        "security/ir.model.access.csv",
        "security/farm_security.xml",
        "data/farm_sequence.xml",
        "data/activity_analytic_account.xml",
        "report/harvest_activity_report_template.xml",
        "report/harvest_activity_report.xml",
        "report/seed_mutation_report_view.xml",
        "report/analytic_cost_report_view.xml",
        "report/seed_delivery_report_view.xml",
        "report/material_usage_report_view.xml",
        "report/cost_production_report.xml",
        "wizard/cost_production_report_view.xml",
        "views/account_analytic_view.xml",
        "views/estate_rainfall_log.xml",
        "views/estate_operation_upkeep_view.xml",
        "report/estate_upkeep_report_view.xml",
        "views/estate_operation_harvest_view.xml",
        "report/estate_harvest_report_view.xml",
        "views/estate_operation_activity_view.xml",
        "views/estate_configuration_view.xml",
        "views/estate_premi_view.xml",
        "views/hr_view_inherit.xml",
        "views/estate_work_book_overview_view.xml",
        "views/estate_bjr_view.xml",
        "views/estate_block_view.xml",
        "views/estate_estate_view.xml",
        "views/product_view.xml",
        "views/farm_seed_mutation_view.xml",
        "views/farm_seed_batch_view.xml",
        "views/res_partner_view.xml",
        "views/farm_menuitem.xml",
        "views/res_config_views.xml",
        "views/product_view.xml",
        "wizard/estate_harvest_labour_line_activity_view.xml",
        "wizard/estate_harvest_labour_penalty_view.xml",
    ],
    "demo": [
        "demo/demo_resource_hr.xml",
        "demo/demo_resource_stock.xml",
        "demo/demo_resource.xml",
        "demo/demo_seed_mutation.xml",
        "demo/demo_rainfall_logs.xml",
        "demo/demo_estate_operation.xml",
    ],
    "installable": True,
    "application": True,
    "license": "OPL-1",
    "module_type": "official",
}
