from . import estate_configuration
from . import estate_estate
from . import estate_block
from . import estate_bjr
from . import product
from . import hr_inherit
from . import res_config_settings
from . import estate_product
from . import estate_seed
from . import estate_operation
from . import estate_operation_harvest
from . import estate_operation_upkeep
from . import estate_premi
from . import estate_harvest_team
from . import account_analytic_plan
from . import estate_rain_logs
from . import res_partner
