from . import weighbridge_scale
from . import weighbridge_partner
from . import weighbridge_product
from . import res_company
from . import res_config_settings
from . import weighbridge_quality_control
from . import weighbridge_quality_type
from . import factory_quality_type
from . import weighbridge_weighbridge
